image: docker:stable-git

# Make sure we can start Docker
services:
  - docker:dind

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache make python3
  - pip3 install docker-compose

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - make build
    - make push
  only:
    refs:
      - master

deploy:
  stage: deploy
  script:
    - make deploy
