image: 7val/gitlab-job

##### HINT!!! If you're runner is not a Docker runner uncomment the following
#####         configuration.

## Make sure we can start Docker
#services:
#  - docker:dind
#
## When using dind, it's wise to use the overlayfs driver for
## improved performance.
#variables:
#  DOCKER_DRIVER: overlay2

##### END HINT

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - time make build
    - time make push
  only:
    refs:
      - master

deploy:
  stage: deploy
  script:
    - time make deploy
  only:
    refs:
      - master
  # only deploy with human intervention
  #when: manual
  artifacts:  # Deployment configuration is saved here
    paths:
      - ./artifacts
