version: '2.3'
services:

  deploy-myapp:
    build:
      context: ./ops/sloppy-deployment
    env_file:
      - environments/development/sloppy.env
      - environments/development/myapp.env
    environment:
      - SLOPPY_APITOKEN
      - DRY_RUN
      - ENVIRONMENT=development
